server:
  port: 10001

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.feiersmart.local:3306/vbox_product?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: product #mysql登录账号
    password: GFLmbm1KeUKLiWhk #mysql登录密码
    type: com.alibaba.druid.pool.DruidDataSource
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 1200000
    maxEvictableIdleTimeMillis: 1500000
    keepAlive: true
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

